// Shared plumbing for the KSA runtime targets (full-stack containers and static
// file serving). Both host apps at <slug>.<APPS_DOMAIN> behind the same Caddy,
// so they share the slug convention, the path-escape guard, and the vhost writer.

import fs from 'fs/promises';
import path from 'path';

export const APPS_DOMAIN = process.env.KSA_APPS_DOMAIN || 'apps.etlaq.sa';
export const APPS_DIR = process.env.KSA_APPS_DIR || '/opt/etlaq-apps';
export const CADDY_APPS_DIR = process.env.KSA_CADDY_APPS_DIR || '/etc/caddy/apps.d';
export const RUNTIME_IMAGE = process.env.KSA_RUNTIME_IMAGE || 'node:22-slim';

export function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40);
}

// Subdomain stays stable across redeploys (and project renames) by reusing the
// slug already recorded in the project's deploy URL. A project that switches
// target (static ↔ full-stack) keeps the same subdomain — resolveSlug is
// target-agnostic, so the one <slug>.caddy file is simply overwritten.
export function resolveSlug(projectId: string, siteName?: string, prevUrl?: string | null): string {
  if (prevUrl) {
    const m = prevUrl.match(new RegExp(`^https://([a-z0-9][a-z0-9-]*)\\.${APPS_DOMAIN.replace(/\./g, '\\.')}$`));
    if (m) return m[1];
  }
  const base = slugify(siteName || '') || 'app';
  return `${base}-${projectId.replace(/-/g, '').slice(0, 8)}`;
}

// Tenant file paths come from the sandbox — never let one escape the app dir.
export function safeJoin(root: string, rel: string): string | null {
  if (path.isAbsolute(rel)) return null;
  const full = path.resolve(root, rel);
  return full.startsWith(root + path.sep) ? full : null;
}

// Write a Caddy vhost for <slug>.<APPS_DOMAIN>. `body` holds the site block's
// inner directives (tab-indented). The caddy-apps.path systemd unit watching
// CADDY_APPS_DIR reloads Caddy; TLS is issued per subdomain via HTTP-01.
export async function writeCaddyVhost(slug: string, body: string): Promise<void> {
  const vhost = `# generated by Etlaq — do not edit; redeploys overwrite this file
${slug}.${APPS_DOMAIN} {
${body}
}
`;
  await fs.writeFile(path.join(CADDY_APPS_DIR, `${slug}.caddy`), vhost, 'utf8');
}
