// Full-stack deploy to the KSA runtime: build and run the generated Next.js app
// as a container ON THIS SERVER, fronted by Caddy at <slug>.<KSA_APPS_DOMAIN>.
// Unlike Vercel, SSR/API routes execute inside KSA — no PDPL transfer.
//
// Mechanics (host prerequisites are in docs/deploy-and-server-setup.md):
//   1. app source  → KSA_APPS_DIR/<slug>/app          (bind-mounted host dir)
//   2. build       → one-shot container: npm install && next build
//   3. run         → long-lived container, 127.0.0.1:<port> → 3000
//   4. route       → KSA_CADDY_APPS_DIR/<slug>.caddy; a systemd path unit
//                    watching that dir reloads Caddy (TLS via HTTP-01)

import fs from 'fs/promises';
import path from 'path';
import { buildEnv } from './env';
import {
  ensureImage, createAndStart, removeContainer, inspectContainer,
  runToCompletion, probeContainerHttp, usedHostPorts, containerLogs,
} from './docker';

const APPS_DOMAIN = process.env.KSA_APPS_DOMAIN || 'apps.etlaq.sa';
const APPS_DIR = process.env.KSA_APPS_DIR || '/opt/etlaq-apps';
const CADDY_APPS_DIR = process.env.KSA_CADDY_APPS_DIR || '/etc/caddy/apps.d';
const RUNTIME_IMAGE = process.env.KSA_RUNTIME_IMAGE || 'node:22-slim';

const PORT_RANGE_START = 34000;
const PORT_RANGE_SIZE = 1000;
const BUILD_TIMEOUT_MS = 15 * 60 * 1000;

// Kept across redeploys so npm/next caches make rebuilds incremental.
const PRESERVED = new Set(['node_modules', '.next', '.npm-cache']);

export interface KsaDeployResult {
  url: string;
  slug: string;
  state: string;
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40);
}

// Subdomain stays stable across redeploys (and project renames) by reusing the
// slug already recorded in the project's deploy URL.
function resolveSlug(projectId: string, siteName?: string, prevUrl?: string | null): string {
  if (prevUrl) {
    const m = prevUrl.match(new RegExp(`^https://([a-z0-9][a-z0-9-]*)\\.${APPS_DOMAIN.replace(/\./g, '\\.')}$`));
    if (m) return m[1];
  }
  const base = slugify(siteName || '') || 'app';
  return `${base}-${projectId.replace(/-/g, '').slice(0, 8)}`;
}

// Tenant file paths come from the sandbox — never let one escape the app dir.
function safeJoin(root: string, rel: string): string | null {
  if (path.isAbsolute(rel)) return null;
  const full = path.resolve(root, rel);
  return full.startsWith(root + path.sep) ? full : null;
}

async function syncSource(appDir: string, files: Record<string, string>) {
  await fs.mkdir(appDir, { recursive: true });
  // Drop stale entries from the previous deploy, keep dependency/build caches.
  for (const entry of await fs.readdir(appDir)) {
    if (!PRESERVED.has(entry)) await fs.rm(path.join(appDir, entry), { recursive: true, force: true });
  }
  for (const [rel, content] of Object.entries(files)) {
    const full = safeJoin(appDir, rel);
    if (!full) continue;
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, content, 'utf8');
  }
}

// .env.production.local outranks every env file a generated app could ship, and
// Next reads it at BUILD time (NEXT_PUBLIC_* inlining) and at runtime alike.
async function writeEnvFile(appDir: string, projectId: string) {
  const { publicEnv, secretEnv } = await buildEnv(projectId);
  const all = { ...publicEnv, ...secretEnv };
  const lines = Object.entries(all).map(([k, v]) => `${k}=${v}`);
  await fs.writeFile(path.join(appDir, '.env.production.local'), lines.join('\n') + '\n', 'utf8');
}

async function allocatePort(slug: string, containerName: string): Promise<number> {
  // Redeploy: keep the port the running (or stopped) app already has, so the
  // Caddy route stays valid even if the reload lags.
  const existing = await inspectContainer(containerName);
  const bound = existing?.HostConfig?.PortBindings?.['3000/tcp']?.[0]?.HostPort;
  if (bound) return parseInt(bound, 10);

  const used = await usedHostPorts();
  let hash = 0;
  for (const ch of slug) hash = (hash * 31 + ch.charCodeAt(0)) >>> 0;
  for (let i = 0; i < PORT_RANGE_SIZE; i++) {
    const port = PORT_RANGE_START + ((hash + i) % PORT_RANGE_SIZE);
    if (!used.has(port)) return port;
  }
  throw new Error('No free port in the KSA app range.');
}

async function writeCaddyRoute(slug: string, port: number) {
  const vhost = `# generated by Etlaq — do not edit; redeploys overwrite this file
${slug}.${APPS_DOMAIN} {
\tencode gzip
\treverse_proxy 127.0.0.1:${port}
}
`;
  await fs.writeFile(path.join(CADDY_APPS_DIR, `${slug}.caddy`), vhost, 'utf8');
}

export async function runKsaDeploy(opts: {
  projectId: string;
  siteName?: string;
  prevUrl?: string | null;
  files: Record<string, string>;
}): Promise<KsaDeployResult> {
  const { projectId, files } = opts;
  if (Object.keys(files).length === 0) throw new Error('No source files found in the sandbox.');

  const slug = resolveSlug(projectId, opts.siteName, opts.prevUrl);
  const appDir = path.join(APPS_DIR, slug, 'app');
  const runName = `etlaq-app-${slug}`;

  await syncSource(appDir, files);
  await writeEnvFile(appDir, projectId);
  await ensureImage(RUNTIME_IMAGE);

  // Build in a throwaway container. The app dir is bind-mounted, so node_modules
  // and .next land on the host and are reused by the runtime container.
  const build = await runToCompletion(
    `etlaq-build-${slug}`,
    {
      Image: RUNTIME_IMAGE,
      WorkingDir: '/app',
      // Same uid as the control app: every file in the bind-mounted dir stays
      // deletable/overwritable on the next redeploy, and tenant code isn't root.
      User: '1001:1001',
      Cmd: ['sh', '-c', 'npm install --no-audit --no-fund && npm run build'],
      Env: ['NEXT_TELEMETRY_DISABLED=1', 'npm_config_cache=/app/.npm-cache', 'CI=1', 'HOME=/app'],
      HostConfig: {
        Binds: [`${appDir}:/app`],
        Memory: 2 * 1024 * 1024 * 1024,
        NetworkMode: 'bridge',
      },
    },
    BUILD_TIMEOUT_MS
  );
  if (build.exitCode !== 0) {
    throw new Error(`App build failed (exit ${build.exitCode}):\n${build.logs.slice(-2000)}`);
  }

  const port = await allocatePort(slug, runName);
  await createAndStart(runName, {
    Image: RUNTIME_IMAGE,
    WorkingDir: '/app',
    User: '1001:1001',
    Cmd: ['sh', '-c', 'npm start -- -p 3000'],
    Env: ['NODE_ENV=production', 'NEXT_TELEMETRY_DISABLED=1', 'HOME=/app'],
    ExposedPorts: { '3000/tcp': {} },
    HostConfig: {
      Binds: [`${appDir}:/app`],
      PortBindings: { '3000/tcp': [{ HostIp: '127.0.0.1', HostPort: String(port) }] },
      RestartPolicy: { Name: 'unless-stopped' },
      Memory: 1024 * 1024 * 1024,
      NetworkMode: 'bridge',
    },
  });

  const up = await probeContainerHttp(runName, 3000);
  if (!up) {
    const logs = await containerLogs(runName).catch(() => '');
    await removeContainer(runName).catch(() => {});
    throw new Error(`App started but never answered HTTP:\n${logs.slice(-2000)}`);
  }

  await writeCaddyRoute(slug, port);

  return { url: `https://${slug}.${APPS_DOMAIN}`, slug, state: 'READY' };
}
