import { NextRequest, NextResponse } from 'next/server';
import { requireOrg, UnauthorizedError } from '@/lib/auth';
import { getProject, getProjectDatabase, upsertProjectDatabase, deleteProjectDatabase } from '@/lib/db/repos';
import { provisionProjectSchema, deprovisionProjectSchema } from '@/lib/db/provision-schema';
import { encrypt, decrypt } from '@/lib/crypto';
import { getTemplate, type Framework, type Template } from '@/lib/templates';
import { getSession } from '@/lib/sandbox/session-store';
import { writeSandboxEnv } from '@/lib/sandbox/write-sandbox-env';

// The Supabase data client the generated app imports (canonical path, so the AI
// never invents one with a bare, unresolvable import). Exposes a per-project
// schema-bound client. Pass a logged-in user's access token (etlaqAuth
// .getAccessToken()) to scope rows by that user via RLS; omit it for public data.
function supabaseClientSource(env: Template['env']) {
  return `// Auto-generated by Etlaq — Supabase data client for this app's isolated schema.
import { createClient } from '@supabase/supabase-js';

const url = ${env.read(env.supabaseUrl)};
const anonKey = ${env.read(env.supabaseAnonKey)};
const schema = ${env.read(env.supabaseSchema)};

export function createSupabaseClient(accessToken) {
  return createClient(url, anonKey, {
    db: { schema },
    global: accessToken ? { headers: { Authorization: 'Bearer ' + accessToken } } : {},
  });
}

// Anonymous client for apps without per-user auth.
export const supabase = createSupabaseClient();
`;
}

// Best-effort: drop the Supabase creds into the live sandbox, install the client,
// and write the canonical data-client module so the generated app can read/write
// immediately. Which dev server to restart depends on the project's framework
// (Vite vs Next.js). Scoped to THIS project's sandbox session — never a shared global.
async function injectIntoSandbox(projectId: string, framework: Framework) {
  const provider = getSession(projectId)?.provider;
  if (!provider) return;
  try {
    // Compose the COMPLETE .env (db + auth + AI) from the DB records so enabling
    // storage never clobbers an already-injected auth or AI proxy token.
    await writeSandboxEnv(projectId, framework);
    const t = getTemplate(framework).env;
    // Next.js App Router has no src/ dir; Vite keeps app code under src/.
    const clientPath = framework === 'nextjs' ? 'lib/supabaseClient.js' : 'src/lib/supabaseClient.js';
    await provider.writeFile(clientPath, supabaseClientSource(t));
    await provider.runShell('npm install @supabase/supabase-js');
    if (framework === 'nextjs') await provider.restartNextServer();
    else await provider.restartViteServer();
  } catch (e) {
    console.error('[database] sandbox injection failed', e);
  }
}

// The generated app connects to the shared self-hosted Supabase; only the
// schema differs per project. URL + anon key are public by design.
function sharedConfig() {
  return {
    url: process.env.NEXT_PUBLIC_SUPABASE_URL || '',
    anonKey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
  };
}

async function requireOwnedProject(id: string) {
  const { orgId } = await requireOrg();
  const project = await getProject(orgId, id);
  return { orgId, project };
}

// GET — current database status for the project
export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const { project } = await requireOwnedProject(id);
    if (!project) return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 });

    const rec = await getProjectDatabase(id);
    if (!rec) return NextResponse.json({ success: true, database: null });

    let creds: any = null;
    try { creds = rec.encryptedCredentials ? JSON.parse(decrypt(rec.encryptedCredentials)) : null; } catch {}
    return NextResponse.json({
      success: true,
      database: { status: rec.status, provider: rec.provider, schema: rec.externalRef, ...creds },
    });
  } catch (error) {
    if (error instanceof UnauthorizedError) return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    return NextResponse.json({ success: false, error: (error as Error).message }, { status: 500 });
  }
}

// POST — provision a per-project schema (idempotent)
export async function POST(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const { project } = await requireOwnedProject(id);
    if (!project) return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 });

    await upsertProjectDatabase(id, { status: 'provisioning' });

    const { schema } = await provisionProjectSchema(id);
    const { url, anonKey } = sharedConfig();

    await upsertProjectDatabase(id, {
      provider: 'supabase',
      externalRef: schema,
      status: 'ready',
      encryptedCredentials: encrypt(JSON.stringify({ url, anonKey, schema })),
    });

    await injectIntoSandbox(id, (project.framework as Framework) || 'vite');

    return NextResponse.json({ success: true, database: { status: 'ready', schema, url, anonKey } });
  } catch (error) {
    const { id } = await params;
    try { await upsertProjectDatabase(id, { status: 'error' }); } catch {}
    if (error instanceof UnauthorizedError) return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    return NextResponse.json({ success: false, error: (error as Error).message }, { status: 500 });
  }
}

// DELETE — tear down the project's schema
export async function DELETE(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const { project } = await requireOwnedProject(id);
    if (!project) return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 });

    await deprovisionProjectSchema(id);
    await deleteProjectDatabase(id);
    return NextResponse.json({ success: true });
  } catch (error) {
    if (error instanceof UnauthorizedError) return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    return NextResponse.json({ success: false, error: (error as Error).message }, { status: 500 });
  }
}
