import { NextRequest, NextResponse } from 'next/server';
import { requireOrg, UnauthorizedError } from '@/lib/auth';
import { getProject, getProjectAuth, upsertProjectAuth, getProjectDatabase } from '@/lib/db/repos';
import { provisionProjectAuth } from '@/lib/auth/provision-auth';
import { isZitadelConfigured } from '@/lib/auth/zitadel';
import { encrypt, decrypt } from '@/lib/crypto';

declare global {
  var activeSandboxProvider: any;
}

// The tiny client the generated app uses: OIDC (PKCE) login against the project's
// Zitadel org, and a helper that hands the access token to supabase-js so PostgREST
// authorizes data calls (RLS scopes rows by the token's `sub`).
function etlaqAuthClientSource() {
  return `// Auto-generated by Etlaq — isolated per-app auth (Zitadel OIDC + Supabase data).
import { UserManager, WebStorageStateStore } from 'oidc-client-ts';

const mgr = new UserManager({
  authority: import.meta.env.VITE_AUTH_ISSUER,
  client_id: import.meta.env.VITE_AUTH_CLIENT_ID,
  redirect_uri: window.location.origin + '/auth/callback',
  post_logout_redirect_uri: window.location.origin,
  response_type: 'code',
  scope: 'openid profile email offline_access',
  userStore: new WebStorageStateStore({ store: window.localStorage }),
  automaticSilentRenew: true,
});

export const etlaqAuth = {
  signIn: () => mgr.signinRedirect(),
  signUp: () => mgr.signinRedirect({ prompt: 'create' }),
  handleCallback: () => mgr.signinRedirectCallback(),
  signOut: () => mgr.signoutRedirect(),
  getUser: () => mgr.getUser(),
  getAccessToken: async () => (await mgr.getUser())?.access_token ?? null,
};
`;
}

async function injectIntoSandbox(opts: {
  issuer: string;
  clientId: string;
  supabase?: { url: string; anonKey: string; schema: string };
}) {
  const provider = global.activeSandboxProvider;
  if (!provider) return;
  try {
    // Write a complete .env (include Supabase data vars if the DB was provisioned,
    // so we don't clobber them — the app needs both).
    let env = '';
    if (opts.supabase) {
      env += `VITE_SUPABASE_URL=${opts.supabase.url}\n`;
      env += `VITE_SUPABASE_ANON_KEY=${opts.supabase.anonKey}\n`;
      env += `VITE_SUPABASE_SCHEMA=${opts.supabase.schema}\n`;
    }
    env += `VITE_AUTH_ISSUER=${opts.issuer}\n`;
    env += `VITE_AUTH_CLIENT_ID=${opts.clientId}\n`;
    await provider.writeFile('.env', env);
    await provider.writeFile('src/lib/etlaqAuth.js', etlaqAuthClientSource());
    await provider.runShell('npm install oidc-client-ts @supabase/supabase-js');
    await provider.restartViteServer();
  } catch (e) {
    console.error('[auth] sandbox injection failed', e);
  }
}

async function requireOwnedProject(id: string) {
  const { orgId } = await requireOrg();
  const project = await getProject(orgId, id);
  return { orgId, project };
}

// GET — current auth status for the project
export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const { project } = await requireOwnedProject(id);
    if (!project) return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 });

    const rec = await getProjectAuth(id);
    return NextResponse.json({
      success: true,
      configured: isZitadelConfigured(),
      auth: rec
        ? { status: rec.status, provider: rec.provider, issuer: rec.issuer, clientId: rec.clientId }
        : null,
    });
  } catch (error) {
    if (error instanceof UnauthorizedError) return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    return NextResponse.json({ success: false, error: (error as Error).message }, { status: 500 });
  }
}

// POST — provision isolated auth (idempotent)
export async function POST(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const { project } = await requireOwnedProject(id);
    if (!project) return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 });

    if (!isZitadelConfigured()) {
      return NextResponse.json(
        { success: false, error: 'Auth backend not configured (ZITADEL_URL/ZITADEL_TOKEN).' },
        { status: 501 }
      );
    }

    await upsertProjectAuth(id, { status: 'provisioning' });
    const { orgId, clientId, issuer } = await provisionProjectAuth(id);

    await upsertProjectAuth(id, {
      provider: 'zitadel',
      orgId,
      clientId,
      issuer,
      status: 'ready',
      encryptedCredentials: encrypt(JSON.stringify({ orgId, clientId, issuer })),
    });

    // Pull the project's Supabase data creds (if any) so injection keeps a complete .env.
    let supabase: { url: string; anonKey: string; schema: string } | undefined;
    const dbRec = await getProjectDatabase(id);
    if (dbRec?.encryptedCredentials) {
      try { supabase = JSON.parse(decrypt(dbRec.encryptedCredentials)); } catch {}
    }

    await injectIntoSandbox({ issuer, clientId, supabase });

    return NextResponse.json({ success: true, auth: { status: 'ready', issuer, clientId } });
  } catch (error) {
    const { id } = await params;
    try { await upsertProjectAuth(id, { status: 'error' }); } catch {}
    if (error instanceof UnauthorizedError) return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    return NextResponse.json({ success: false, error: (error as Error).message }, { status: 500 });
  }
}
