import { NextRequest, NextResponse } from 'next/server';
import { requireOrg, UnauthorizedError } from '@/lib/auth';
import { getProject, getProjectAuth, upsertProjectAuth } from '@/lib/db/repos';
import { provisionProjectAuth } from '@/lib/auth/provision-auth';
import { isZitadelConfigured } from '@/lib/auth/zitadel';
import { encrypt } from '@/lib/crypto';
import { getTemplate, type Framework, type Template } from '@/lib/templates';
import { writeSandboxEnv } from '@/lib/sandbox/write-sandbox-env';
import { getSession } from '@/lib/sandbox/session-store';

// The tiny client the generated app uses: OIDC (PKCE) login against the project's
// Zitadel org, and a helper that hands the access token to supabase-js so PostgREST
// authorizes data calls (RLS scopes rows by the token's `sub`).
function etlaqAuthClientSource(env: Template['env']) {
  return `// Auto-generated by Etlaq — isolated per-app auth (Zitadel OIDC + Supabase data).
// SSR-safe: the UserManager touches window/localStorage, so it is constructed
// lazily and ONLY in the browser. During server render / next build prerender
// every method is a harmless no-op (getUser -> null), so pages that import this
// module never crash with "window is not defined".
import { UserManager, WebStorageStateStore } from 'oidc-client-ts';

let _mgr = null;
const inBrowser = () => typeof window !== 'undefined';
function mgr() {
  if (!_mgr) {
    _mgr = new UserManager({
      authority: ${env.read(env.authIssuer)},
      client_id: ${env.read(env.authClientId)},
      redirect_uri: window.location.origin + '/auth/callback',
      post_logout_redirect_uri: window.location.origin,
      response_type: 'code',
      scope: 'openid profile email offline_access',
      userStore: new WebStorageStateStore({ store: window.localStorage }),
      automaticSilentRenew: true,
    });
  }
  return _mgr;
}

// Auto-complete the login redirect. After the user signs in, the provider sends
// them back with ?code=&state= in the URL. We exchange it here on load and clean the
// URL, so login works even when the app has no dedicated /auth/callback route (the
// common case). getUser()/getAccessToken() await this so the app never reads a null
// user during the exchange.
let _ready = Promise.resolve();
if (inBrowser()) {
  const _p = new URLSearchParams(window.location.search);
  if (_p.has('code') && _p.has('state')) {
    _ready = mgr().signinRedirectCallback()
      .then(() => { window.history.replaceState({}, document.title, '/'); })
      .catch(() => { window.history.replaceState({}, document.title, '/'); });
  }
}

export const etlaqAuth = {
  // prompt:'login' forces the login screen even when Zitadel still has an active
  // SSO session — so after signing out (which only clears local tokens) the user
  // is asked to log in and CAN switch to a different account, instead of being
  // silently re-authenticated as the same user.
  signIn: () => (inBrowser() ? mgr().signinRedirect({ prompt: 'login' }) : Promise.resolve()),
  signUp: () => (inBrowser() ? mgr().signinRedirect({ prompt: 'create' }) : Promise.resolve()),
  // Kept for backward compatibility; login is now completed automatically on load.
  handleCallback: () => (inBrowser() ? _ready.then(() => mgr().getUser()) : Promise.resolve(null)),
  // Local sign-out: clear this app's tokens and return home. We deliberately do
  // NOT call signoutRedirect() — the OIDC end-session endpoint bounces to a
  // hosted logout UI that isn't reliably available, leaving users on a raw
  // "Not Found" page. Clearing the local session logs them out of THIS app.
  signOut: async () => {
    if (!inBrowser()) return;
    try { await mgr().removeUser(); } catch { /* already gone */ }
    window.location.href = '/';
  },
  // ASYNC — returns a Promise. You MUST await it: \`const user = await etlaqAuth.getUser()\`.
  // Resolves to the signed-in user, or null when nobody is logged in.
  getUser: async () => { if (!inBrowser()) return null; await _ready; return mgr().getUser(); },
  isLoggedIn: async () => { if (!inBrowser()) return false; await _ready; return !!(await mgr().getUser()); },
  getAccessToken: async () => { if (!inBrowser()) return null; await _ready; return (await mgr().getUser())?.access_token ?? null; },
};
`;
}

async function injectIntoSandbox(opts: { projectId: string; framework: Framework }) {
  const provider = getSession(opts.projectId)?.provider;
  if (!provider) return;
  try {
    // Compose the COMPLETE .env (db + auth + AI) from the DB records so provisioning
    // auth never clobbers an already-injected database or AI proxy token.
    await writeSandboxEnv(opts.projectId, opts.framework);
    const t = getTemplate(opts.framework).env;
    // Next.js App Router has no src/ dir; put the client under lib/.
    const authClientPath = opts.framework === 'nextjs' ? 'lib/etlaqAuth.js' : 'src/lib/etlaqAuth.js';
    await provider.writeFile(authClientPath, etlaqAuthClientSource(t));
    await provider.runShell('npm install oidc-client-ts @supabase/supabase-js');
    if (opts.framework === 'nextjs') await provider.restartNextServer();
    else await provider.restartViteServer();
  } catch (e) {
    console.error('[auth] sandbox injection failed', e);
  }
}

async function requireOwnedProject(id: string) {
  const { orgId } = await requireOrg();
  const project = await getProject(orgId, id);
  return { orgId, project };
}

// GET — current auth status for the project
export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const { project } = await requireOwnedProject(id);
    if (!project) return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 });

    const rec = await getProjectAuth(id);
    return NextResponse.json({
      success: true,
      configured: isZitadelConfigured(),
      auth: rec
        ? { status: rec.status, provider: rec.provider, issuer: rec.issuer, clientId: rec.clientId }
        : null,
    });
  } catch (error) {
    if (error instanceof UnauthorizedError) return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    return NextResponse.json({ success: false, error: (error as Error).message }, { status: 500 });
  }
}

// POST — provision isolated auth (idempotent)
export async function POST(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const { project } = await requireOwnedProject(id);
    if (!project) return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 });

    if (!isZitadelConfigured()) {
      return NextResponse.json(
        { success: false, error: 'Auth backend not configured (ZITADEL_URL/ZITADEL_TOKEN).' },
        { status: 501 }
      );
    }

    await upsertProjectAuth(id, { status: 'provisioning' });
    const { orgId, clientId, issuer } = await provisionProjectAuth(id);

    await upsertProjectAuth(id, {
      provider: 'zitadel',
      orgId,
      clientId,
      issuer,
      status: 'ready',
      encryptedCredentials: encrypt(JSON.stringify({ orgId, clientId, issuer })),
    });

    await injectIntoSandbox({ projectId: id, framework: (project.framework as Framework) || 'vite' });

    return NextResponse.json({ success: true, auth: { status: 'ready', issuer, clientId } });
  } catch (error) {
    const { id } = await params;
    try { await upsertProjectAuth(id, { status: 'error' }); } catch {}
    if (error instanceof UnauthorizedError) return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    return NextResponse.json({ success: false, error: (error as Error).message }, { status: 500 });
  }
}
