import { getSession } from '@/lib/sandbox/session-store';
import { getTemplate, type Framework, type Template } from '@/lib/templates';
import { writeSandboxEnv } from '@/lib/sandbox/write-sandbox-env';

// The Supabase data client the generated app imports (canonical path, so the AI
// never invents one with a bare, unresolvable import). Exposes a per-project
// schema-bound client. Pass a logged-in user's access token (etlaqAuth
// .getAccessToken()) to scope rows by that user via RLS; omit it for public data.
export function supabaseClientSource(env: Template['env']) {
  return `// Auto-generated by Etlaq — Supabase data client for this app's isolated schema.
import { createClient } from '@supabase/supabase-js';

const url = ${env.read(env.supabaseUrl)};
const anonKey = ${env.read(env.supabaseAnonKey)};
const schema = ${env.read(env.supabaseSchema)};

export function createSupabaseClient(accessToken) {
  return createClient(url, anonKey, {
    db: { schema },
    global: accessToken ? { headers: { Authorization: 'Bearer ' + accessToken } } : {},
  });
}

// Anonymous client for apps without per-user auth.
export const supabase = createSupabaseClient();
`;
}

// Best-effort: drop the Supabase creds into the live sandbox, install the client
// dependency, and write the canonical data-client module so the generated app can
// read/write immediately. `@supabase/supabase-js` is installed out-of-band here
// (never via the AI's <package> tags nor the base scaffold), so any flow that
// rebuilds a sandbox for a DB-enabled project — provisioning OR restore — must run
// this, otherwise lib/supabaseClient.js's import fails to resolve at build time.
// Which dev server to restart depends on the project's framework (Vite vs Next.js).
// Scoped to THIS project's sandbox session — never a shared global.
export async function injectSupabaseIntoSandbox(projectId: string, framework: Framework) {
  const provider = getSession(projectId)?.provider;
  if (!provider) return;
  try {
    // Compose the COMPLETE .env (db + auth + AI) from the DB records so enabling
    // storage never clobbers an already-injected auth or AI proxy token.
    await writeSandboxEnv(projectId, framework);
    const t = getTemplate(framework).env;
    // Next.js App Router has no src/ dir; Vite keeps app code under src/.
    const clientPath = framework === 'nextjs' ? 'lib/supabaseClient.js' : 'src/lib/supabaseClient.js';
    await provider.writeFile(clientPath, supabaseClientSource(t));
    await provider.runShell('npm install @supabase/supabase-js');
    if (framework === 'nextjs') await provider.restartNextServer();
    else await provider.restartViteServer();
  } catch (e) {
    console.error('[inject-supabase] sandbox injection failed', e);
  }
}
