import { getSession } from '@/lib/sandbox/session-store';
import { type Framework } from '@/lib/templates';

// The tiny client a role-aware generated app imports to manage its team. Wraps the
// per-project Supabase data client (authenticated as the logged-in user) around the
// app_members roster + the SECURITY DEFINER RPCs created by provisionProjectRoles.
// Sits next to supabaseClient.js and etlaqAuth.js, so relative imports resolve in
// both templates (Vite src/lib, Next lib/).
export function etlaqTeamClientSource() {
  return `// Auto-generated by Etlaq — team roles (owner / manager / employee).
import { createSupabaseClient } from './supabaseClient';
import { etlaqAuth } from './etlaqAuth';

async function db() {
  return createSupabaseClient(await etlaqAuth.getAccessToken());
}

export const etlaqTeam = {
  // Call ONCE right after the user signs in. The first person to ever call it
  // becomes 'owner'; everyone after starts as 'employee'. Returns their role.
  claim: async () => {
    const u = await etlaqAuth.getUser();
    const c = await db();
    const { data } = await c.rpc('app_claim_membership', {
      p_email: u?.profile?.email ?? null,
      p_name: u?.profile?.name ?? u?.profile?.preferred_username ?? null,
    });
    return data; // 'owner' | 'manager' | 'employee'
  },
  // The current user's role.
  myRole: async () => {
    const { data } = await (await db()).rpc('app_role');
    return data;
  },
  // The full roster — any signed-in member can read it (for assignment dropdowns).
  members: async () => {
    const { data } = await (await db()).from('app_members').select('*').order('created_at');
    return data ?? [];
  },
  // Owner-only (enforced by the database): change a member's role / assign a manager.
  setRole: async (userId, role) => (await db()).from('app_members').update({ role }).eq('user_id', userId),
  setManager: async (userId, managerId) =>
    (await db()).from('app_members').update({ manager_id: managerId }).eq('user_id', userId),
};
`;
}

// Write the etlaqTeam client into the live sandbox. The DB-side roles infra (table +
// functions + policies) is provisioned separately by provisionProjectRoles (invoked
// from createTables when an `org` table is declared). No extra npm install — it reuses
// @supabase/supabase-js, already installed for the data client.
export async function injectRolesIntoSandbox(projectId: string, framework: Framework): Promise<void> {
  const provider = getSession(projectId)?.provider;
  if (!provider) return;
  try {
    const clientPath = framework === 'nextjs' ? 'lib/etlaqTeam.js' : 'src/lib/etlaqTeam.js';
    await provider.writeFile(clientPath, etlaqTeamClientSource());
  } catch (e) {
    console.error('[inject-roles] sandbox injection failed', e);
  }
}
