import { getSession } from '@/lib/sandbox/session-store';
import { type Framework } from '@/lib/templates';
import { bucketForProject, type FileAccess } from '@/lib/db/provision-storage';

// The etlaqFiles client the generated app imports for uploads. For public file
// access it talks to storage anonymously; for private/org it authenticates as the
// logged-in user (so storage RLS scopes files by owner_id = their sub). Generated
// per access so a public/no-auth app never imports the (absent) auth client.
export function etlaqFilesClientSource(bucket: string, access: FileAccess) {
  const authed = access !== 'public';
  const head = authed
    ? `import { createSupabaseClient } from './supabaseClient';
import { etlaqAuth } from './etlaqAuth';

async function db() { return createSupabaseClient(await etlaqAuth.getAccessToken()); }`
    : `import { supabase } from './supabaseClient';

async function db() { return supabase; }`;

  return `// Auto-generated by Etlaq — file uploads for this app.
${head}

const BUCKET = ${JSON.stringify(bucket)};

export const etlaqFiles = {
  // Upload a File/Blob (e.g. from <input type="file">). Returns { key } to store in
  // your data, or { error }. Optionally put it in a folder.
  upload: async (file, folder = '') => {
    const c = await db();
    const path = (folder ? folder.replace(/\\/+$/, '') + '/' : '') + Date.now() + '-' + (file.name || 'file');
    const { data, error } = await c.storage.from(BUCKET).upload(path, file, { upsert: false });
    return { key: data?.path ?? null, error };
  },
  // A temporary link to view/download a private file (default 1 hour).
  url: async (key, expiresIn = 3600) => {
    const c = await db();
    const { data } = await c.storage.from(BUCKET).createSignedUrl(key, expiresIn);
    return data?.signedUrl ?? null;
  },
  list: async (folder = '') => {
    const c = await db();
    const { data } = await c.storage.from(BUCKET).list(folder);
    return data ?? [];
  },
  remove: async (key) => {
    const c = await db();
    return c.storage.from(BUCKET).remove([key]);
  },
};
`;
}

export async function injectStorageIntoSandbox(
  projectId: string,
  framework: Framework,
  access: FileAccess,
): Promise<void> {
  const provider = getSession(projectId)?.provider;
  if (!provider) return;
  try {
    const clientPath = framework === 'nextjs' ? 'lib/etlaqFiles.js' : 'src/lib/etlaqFiles.js';
    await provider.writeFile(clientPath, etlaqFilesClientSource(bucketForProject(projectId), access));
  } catch (e) {
    console.error('[inject-storage] sandbox injection failed', e);
  }
}
